// <auto-generated />
namespace Animals.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Animals11d : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Animals11d));
        
        string IMigrationMetadata.Id
        {
            get { return "202306020544420_Animals11d"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
